### ISSUE TITLE
Backcover appears in PDF, but not in HTML

### ISSUE THREAD

**Issue by sachin-suresh-rapyuta** [useblocks/sphinx-simplepdf#49] opened 2022-10-17 04:31 UTC
With the below configuration in `conf.py`, I am also getting the cover image at the end of the PDF. 
Is this a backcover for the PDF? If so, why I am not able to see this image in the simplepdf html?

```
simplepdf_vars = {
    'primary-opaque': '#E11A27',
    'cover-bg': 'url(User_guide_pdf_cover.png) no-repeat center',
    'primary': '#E11A27',
    'secondary': '#E11A27',
    'cover': '#ffffff',
    'white': '#ffffff',
    'links': '#2980B9',
    'top-left-content': 'counter(page)',
    'top-center-content': '',
    'top-right-content': '"My Documentation"',
    'bottom-left-content': 'counter(page)',
    'bottom-center-content': '',
    'bottom-right-content': 'string(heading)'
}
```

**Comment by danwos** [comment] 2022-10-17 06:36
Yes, it's a back cover for the PDF and is currently hard-coded.
So there is no option to deactivate it.

it is part of the simplepdf HTML build and the resulting HTML code, but may not be configured via CSS the right way, so that you can easily see it.
But that's not needed, as the simplepdf HTML artifacts are just an intermediate step and should not be used by the user directly.

I close this issue as it is not a bug, but feel free to reopen if you have further requests.

**Closed by danwos** 2022-10-17 06:36 UTC

**Comment by sachin-suresh-rapyuta** [comment] 2022-10-19 08:44
So what if I need to include a custom back cover png? Where and how I can configure it?

**Comment by danwos** [comment] 2022-10-19 09:15
There is no way to configure it via the conf.py, yet.

The only way I see is custom CSS and even a custom template file.
But I don't know any implementation of it and I'm currently too busy to make some tests here.
