### ISSUE TITLE
PDF theme not pointing to latest theme without activating Virtualenv

### ISSUE THREAD

**Issue by sachin-suresh-rapyuta** [useblocks/sphinx-simplepdf#38] opened 2022-09-20 08:50 UTC
> @1kastner: Thanks for the test. Your output gave me the hint to recheck my path-calculation, as it may not work on windows. And indeed, one path may not have worked.
> 
> Can you please pull the latest commit and recheck it again? Thanks.

@danwos I guess still the new theme is not picking without activating virtualenv. I just tested this twice with & without virtual env. This is what I observed:

**Case 1:** When `virtualenv` (simplepdfvenv2) is activated:

```
$ which sphinx-build
/home/sachin/Workspace/my-project-path/docs/simplepdfvenv2/bin/sphinx-build
```
PDF Result:

- (green cover page) PDF is generated without issues

**Case 2:** When `virtualenv` is not activated:

```
$ which sphinx-build
/usr/local/bin/sphinx-build
```
PDF Result:

- (red cover page) PDF is generated. i.e., with old styles.

**Comment by danwos** [comment] 2022-09-20 09:20
That's for me the normal case.

It all depends on what environment you are using and in which one you have installed what kind of Sphinx-SimplePDF version.

If you have e.g. 2 environments (1 system-wide, 1 virtualenv), you need to install it in both separately.
Their installation is completely separated and they do not have access to each other.

So in your virtualenv you could install the latest version from github.
In a system-wide env the latest release from PyPi (which would not contain all the fixes yet.)

In my understanding, there is nothing Sphinx-SimplePDF can do here.
It's all about how the virtualenvs get handled.

So in your case, I would simply install Sphinx-SimplePDF again with deactivated venv:
`pip install --upgrade git+https://github.com/useblocks/sphinx-simplepdf.git@main`
Then it should work.

**Comment by sachin-suresh-rapyuta** [comment] 2022-09-20 09:32
Yes, I did that too in my deactivated env. Removed build folder and ran `make simplepdf`, I get old theme pdf.

**Comment by sachin-suresh-rapyuta** [comment] 2022-10-13 05:45
@danwos - Would be happy to hear if this was fixed. Was there something I am missing from the above commands that I am running in deactivated env?

**Comment by danwos** [comment] 2022-10-17 06:45
I have some problems with seeing the described behavior as a problem inside Sphinx-SimplePDF.

Sphinx-SimplePDF knows nothing about old themes. It only knows the current installed one.
And the path to it is hard-coded and not somehow calculated dynamically based on other factors.

So for me it sounds like 2 envs are used, and usage or installation is done somehow incorrectly.

As I'm also unable to reproduce it, I am closing this issue for now.
But feel free to reopen, if any new information is coming up.

**Closed by danwos** 2022-10-17 06:45 UTC

**Comment by sachin-suresh-rapyuta** [comment] 2022-10-18 02:13
Had to completely remove sphinx-simplepdf and reinstalled it. It seems fine for now. Although, the simplepdf version from `pip list` shows `1.3.0`. Not sure if this is the right and latest version. If I remember right, I had `1.4.0` when I used virtual env.

**Comment by sachin-suresh-rapyuta** [comment] 2022-10-26 04:25
@danwos - If I need to keep one installation with a new PDF theme, what do you suggest to uninstall? Like remove Python3 completely and reinstall? What is the path I need to be on to avoid all ambiguities?

**Comment by danwos** [comment] 2022-10-26 06:12
To be honest I have no idea what is going wrong on your machine.
Your description sounds all valid and that's the way how I would do it as well.

Last thing, which is coming into my mind: Can you install it via
``pip3 install --upgrade -e ../../../../../Test/sphinx-simplepdf``?

``--upgrade`` makes sure its gets installed, even if ``pip`` things the version has not changed.

``-e`` installs it in ``dev mode``, which means no files get copied to the pythone-env. Instead, a symbolic link to `` ../../../../../Test/sphinx-simplepdf`` is set. So each change in this folder is directly available in your system-wide Python env.
If ``-e`` is not used, with each change in the repo, you also have to ``pip install`` it again.

**Comment by sachin-suresh-rapyuta** [comment] 2022-10-26 06:27
Ah!! That works. Hopefully, I tested it properly in a non-virtual env. 
Just a quick question: When are you planning to push the new theme, and latest changes to pip instead of the Github Test folder?

**Comment by danwos** [comment] 2022-10-26 06:30
It is already, 1.4.0 is available on PyPI: https://pypi.org/project/sphinx-simplepdf/

The upcoming version 1.5 is containing mostly new features, but not so many theme bugfixes.

**Comment by sachin-suresh-rapyuta** [comment] 2022-10-26 06:32
Ok, if it is already on PyPI, why was I still using `pip3 install --upgrade -e ../../../../../Test/sphinx-simplepdf` to get the new theme? Was it recently moved? 
So, If I uninstall the simplepdf and just use `pip install sphinx-simplepdf`, I should get the latest theme?

**Comment by danwos** [comment] 2022-10-26 06:34
Yes, ``pip install sphinx-simplepdf`` should be enough.

> Ok, if it is already on PyPI, why was I still using pip3 install --upgrade -e ../../../../../Test/sphinx-simplepdf to get the new theme? Was it recently moved?

Was released ~4 weeks ago.

**Comment by sachin-suresh-rapyuta** [comment] 2022-10-26 06:42
Oh, this is the issue:
I again completely uninstalled simplepdf.

Now, I just tried `pip install sphinx-simplepdf`. I get `Successfully installed sphinx-simplepdf-1.3.0`. --> I get old theme PDF
But when I `pip3 install --upgrade -e ../../../../../Test/sphinx-simplepdf`, I get: `Successfully installed sphinx-simplepdf-1.4.0`.   ---> I get new theme PDF.

**Comment by danwos** [comment] 2022-10-26 06:45
> Now, I just tried `pip install sphinx-simplepdf`. I get `Successfully installed sphinx-simplepdf-1.3.0`...

I'm confused, you should get version ``1.4.0``, as this is the latest on PyPI.
Are you using any company internal PyPI caches (e.g. Artifactory) or so?

**Comment by sachin-suresh-rapyuta** [comment] 2022-10-26 06:51
Here is the traceback. Tried the below 2 commands. Both installs `1.3.0` :(

```
pip install --upgrade sphinx-simplepdf

Defaulting to user installation because normal site-packages is not writeable
Collecting sphinx-simplepdf
  Using cached sphinx_simplepdf-1.3.0-py3-none-any.whl
...
...
Installing collected packages: sphinx-simplepdf
Successfully installed sphinx-simplepdf-1.3.0
```

And now with `--no-cache-dir` option:

```
pip install --upgrade sphinx-simplepdf --no-cache-dir
Defaulting to user installation because normal site-packages is not writeable
Collecting sphinx-simplepdf
  Downloading sphinx-simplepdf-1.3.0.tar.gz (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 27.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
...
...
Building wheels for collected packages: sphinx-simplepdf
  Building wheel for sphinx-simplepdf (setup.py) ... done
  Created wheel for sphinx-simplepdf: filename=sphinx_simplepdf-1.3.0-py3-none-any.whl size=1754139 sha256=0b87471e3a6971c718b5786e91208c6ca91a3d015c53cfdb13fac7ef24b4153c
  Stored in directory: /tmp/pip-ephem-wheel-cache-f7vfi3gb/wheels/9b/49/99/6f8cf450d6b43c83feabc89e0fea981cc5a3a3f0f280e8892e
Successfully built sphinx-simplepdf
Installing collected packages: sphinx-simplepdf
Successfully installed sphinx-simplepdf-1.3.0
```

**Comment by danwos** [comment] 2022-10-26 06:55
You are right, I can reproduce it.
Let me create a fresh, clean 1.5.0 and deploy it. One moment please...

**Comment by danwos** [comment] 2022-10-26 07:16
``1.5.0`` got released.
Downloading the correct version works on my side.

**Comment by sachin-suresh-rapyuta** [comment] 2022-10-26 07:36
I have 1.5.0 now. But are you able to see the new theme. I cleaned the build folder and with `make simplepdf`, I am getting the old PDF.
